<a href="https://colab.research.google.com/github/ashtonsouthwick/DSPS_ASouthwick/blob/main/Labs/earthquake_data_munging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
earthquakes = pd.read_csv('https://raw.githubusercontent.com/fedhere/DSPS_FBianco/refs/heads/main/data/earthquakes.csv',
            sep=r'\s+' )

In [3]:
earthquakes.shape

(70798, 13)

In [4]:
earthquakes.head(3)

,#YYY/MM/DD,HH:mm:SS.ss,ET,GT,MAG,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
0,1984/01/01,01:30:57.52,eq,l,2.02,c,33.246,-116.433,1.6,C,28255,13,17
1,1984/01/01,05:31:34.16,eq,l,2.12,c,32.945,-116.295,5.4,C,28259,18,42
2,1984/01/01,06:59:05.14,eq,l,2.43,c,33.343,-117.628,5.6,C,28260,13,30

In [5]:
earthquakes.tail(3)

,#YYY/MM/DD,HH:mm:SS.ss,ET,GT,MAG,M,LAT,LON,DEPTH,Q,EVID,NPH,NGRM
70795,2002/12/29,20:21:28.73,eq,l,2.07,l,35.32150,-118.66617,1.9,A,9874749,53,277
70796,2002/12/30,21:51:52.55,eq,l,2.31,l,35.31867,-118.66250,1.5,A,9875017,66,404
70797,2002/12/30,23:38:49.79,eq,l,2.05,l,35.31450,-118.66333,1.9,A,9875061,54,283

In [6]:
earthquakes.columns

Index(['#YYY/MM/DD', 'HH:mm:SS.ss', 'ET', 'GT', 'MAG', 'M', 'LAT', 'LON',
       'DEPTH', 'Q', 'EVID', 'NPH', 'NGRM'],
      dtype='object')

In [7]:
earthquakes = earthquakes[['#YYY/MM/DD', 'HH:mm:SS.ss', 'MAG']]

In [8]:
earthquakes.dtypes

#YYY/MM/DD      object
HH:mm:SS.ss     object
MAG            float64
dtype: object

In [9]:
earthquakes.rename({"#YYY/MM/DD": "date", "HH:mm:SS.ss": "time", "MAG": "mag"}, axis=1, inplace=True) #axis=1 indicates renaming by column

In [10]:
earthquakes

             date         time   mag
0      1984/01/01  01:30:57.52  2.02
1      1984/01/01  05:31:34.16  2.12
2      1984/01/01  06:59:05.14  2.43
3      1984/01/01  11:10:25.29  2.07
4      1984/01/01  19:38:19.79  2.13
...           ...          ...   ...
70793  2002/12/29  19:37:24.56  2.21
70794  2002/12/29  20:17:33.40  2.02
70795  2002/12/29  20:21:28.73  2.07
70796  2002/12/30  21:51:52.55  2.31
70797  2002/12/30  23:38:49.79  2.05

[70798 rows x 3 columns]

In [11]:
earthquakes.describe()

                mag
count  70798.000000
mean       2.417826
std        0.407683
min        2.000000
25%        2.120000
50%        2.300000
75%        2.590000
max        7.100000

In [12]:
earthquakes['newdate'] = earthquakes['date'].map(pd.to_datetime)

In [13]:
earthquakes['datetime'] = earthquakes['date'] + " " + earthquakes['time']
earthquakes['datetime']

0        1984/01/01 01:30:57.52
1        1984/01/01 05:31:34.16
2        1984/01/01 06:59:05.14
3        1984/01/01 11:10:25.29
4        1984/01/01 19:38:19.79
                  ...
70793    2002/12/29 19:37:24.56
70794    2002/12/29 20:17:33.40
70795    2002/12/29 20:21:28.73
70796    2002/12/30 21:51:52.55
70797    2002/12/30 23:38:49.79
Name: datetime, Length: 70798, dtype: object

In [15]:
# earthquakes['newdatetime'] = earthquakes['datetime'].map(pd.to_datetime)

In [16]:
for i in earthquakes.index:
  if earthquakes.loc[i, "time"].endswith('60.00'):
    print(earthquakes.loc[i,'time'])
    earthquakes.loc[i, 'time'] = earthquakes.loc[i, 'time'][:6] + "59.99"
    print(earthquakes.loc[i, 'time'])

04:48:60.00
04:48:59.99
14:19:60.00
14:19:59.99
21:48:60.00
21:48:59.99
15:34:60.00
15:34:59.99
06:41:60.00
06:41:59.99

In [17]:
earthquakes['datetime'] = earthquakes['date'] + ' ' + earthquakes['time']
earthquakes['newdatetime'] = earthquakes['datetime'].map(pd.to_datetime)
earthquakes['newdatetime']

0       1984-01-01 01:30:57.520
1       1984-01-01 05:31:34.160
2       1984-01-01 06:59:05.140
3       1984-01-01 11:10:25.290
4       1984-01-01 19:38:19.790
                  ...
70793   2002-12-29 19:37:24.560
70794   2002-12-29 20:17:33.400
70795   2002-12-29 20:21:28.730
70796   2002-12-30 21:51:52.550
70797   2002-12-30 23:38:49.790
Name: newdatetime, Length: 70798, dtype: datetime64[ns]

In [18]:
earthquakes.describe()

,mag,newdate,newdatetime
count,70798.000000,70798,70798
mean,2.417826,1992-11-07 16:14:28.092318976,1992-11-08 04:14:59.083973376
min,2.000000,1984-01-01 00:00:00,1984-01-01 01:30:57.520000
25%,2.120000,1988-05-05 00:00:00,1988-05-05 20:49:20.964999936
50%,2.300000,1992-07-18 00:00:00,1992-07-18 06:27:56.530000
75%,2.590000,1996-10-29 00:00:00,1996-10-29 15:31:47.564999936
max,7.100000,2002-12-30 00:00:00,2002-12-30 23:38:49.790000
std,0.407683,NaN,NaN

In [19]:
earthquakes['newdatetime'].mean()

Timestamp('1992-11-08 04:14:59.083973376')

In [20]:
earthquakes['newdatetime'].std()

Timedelta('1826 days 19:14:43.046994976')

In [21]:
earthquakes['newdatetime'].diff() # check if ordered chronologically

0                          NaT
1       0 days 04:00:36.640000
2       0 days 01:27:30.980000
3       0 days 04:11:20.150000
4       0 days 08:27:54.500000
                 ...
70793   0 days 00:00:30.140000
70794   0 days 00:40:08.840000
70795   0 days 00:03:55.330000
70796   1 days 01:30:23.820000
70797   0 days 01:46:57.240000
Name: newdatetime, Length: 70798, dtype: timedelta64[ns]

# The above was from close, below is homework

select valuable data
Starting here is stuff we did not do together in class but is part of the homework due on 9/17

Following the description in Section 2 of Corral 2018 I removed all data that did not belong to a "stationary" period. Third paragraph section 2 of Corral 2018. You can see the cell of code I used to do this here at no points cost, cause it was a bit tricky, but I encourage you to try and do it yourself. If you can do it in fewer lines than I did its automatically +5 points (just turning the loop into a list comprehension does not count. That is an obvious way to decrease the number of lines of code; I did not do it simply to enhance readability.)

In [ ]:
# your code here
ss = []

In [ ]:
print ("the {} timestamp pairs that are the boundaries of good data periods are:".format(len(ss)))

The following cell of code shows you the array of bool values (True/False) which I create to use as an index to the input array: when used as an index, a technique called "broadcasting" in python, will select only elements of the original array where the index array value is True. something like Try:

In [ ]:
a = np.array([0, 1, 2])
a, a[[True, False, True]]

For each of the 11 valid periods I create a condition datetime >= period_start AND datetime <= period_end where AND is a product of booleans: True * False = False.

I want to take all chinks of data that satisfy this condition for any of the 11 chunks of time so that is a logical OR operator, or a sum of Booleans: True + False = True

This is because True really corresponds to "not 0" and False to "0". So "not 0" * 0 = 0 and "not 0" + 0 = not 0

In [ ]:
# your code here
print ("there are {} earthquakes falling in the selected stationary periods".
       format(gooddates.sum()))

In [ ]:
# your code here: broadcasting to create a dataframe with the good dates only
eqGoodData.shape

In [ ]:
eqGoodData.head()

Now what you really want is the time interval between earthquakes for all events greater than some magnitude m, while all you have are the date and time of the events

You can remove earthquakes smaller than magnitude 2 by, again, broadcasting. How would that look like?

In [ ]:
# your code here
eqGoodData.shape #look like for my data it was not needed! that is because I chose M>2 when when I downloaded the data

You can get the time between consecutive earthquakes with the method diff() of numpy arrays (as done in class).

In [ ]:
#your code here
eqGoodData.shape

In [ ]:
eqGoodData.head()

In [ ]:
eqGoodData.describe()

Note that the first entry will be NaT which is Not a Time (corresponding to nan for numerical variables) or maybe a negative number (depends on your exact operations above). You should remove it

In [ ]:
# your code here
eqGoodData.head()

data exploration
At this point you should wonder if this is the final dataset that you want to use and if anything is weird or suspicious about it. Visualize the distribution. A good way to visualize distributions is a histogram which you can prodice with pl.hist() or as a method of your dataframe series as df[SeriesName].plot(kind="hist"). Produce a plot like the one below (label the axis! and describe it with a caption!). To get the logarithmic y axis you can se logy=True, for example. in your df[SeriesName].plot call.

The thing that worries me is that by removing some sections of the data to use only stationary periods we created some artificially large gaps: gaps of order ~month. How many nanoseconds in a month? remove all gaps that are larger than about a month and see how the distribution looks (make another histogram).

In [22]:
# your code here